/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "bot": {
        "welcome": string;
        "enterEmail": string;
        "sendPassword": string;
        "downloadingFile": string;
        "mediaTypeNotSupported": string;
        "name": string;
        "activated": string;
        "error": {};
        "scenes": {
            "initization": {
                "leave": string;
            };
            "login": {
                "leave": string;
                "ban": string;
                "newUser": string;
            };
            "enterEmail": {
                "enter": string;
                "noEmail": string;
                "leave": string;
            };
            "save": {
                "onSceneEnter": string;
                "success": string;
            };
        };
        "menu": {
            "keyboard": {
                "enterEmail": string;
            };
        };
    };
    "exception": {
        "userNotActivate": string;
        "invalidPassword": string;
        "imageNotFound": string;
        "userNotFound": string;
        "dirNotFound": string;
        "userAlreadyExists": string;
        "formatSMHDWY": string;
        "downloadFile": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
