stages:
  - build
  - deploy

build-docker:
  stage: build
  image: docker:stable
  tags:
    - docker
  only:
    - master
  services:
    - name: docker:dind
      alias: localhost

  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://localhost:2375"
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u Deployer -p ${ACCESS_TOKEN_REGISTRY} ${URL_REGISTRY}
  script:
    - docker build -t ${URL_REGISTRY}/${PATH_PROJECT}:${CI_COMMIT_REF_NAME} --build-arg branch=${CI_COMMIT_REF_NAME} .
    - docker push ${URL_REGISTRY}/${PATH_PROJECT}:${CI_COMMIT_REF_NAME}

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - ssh ${DEPLOY_SERVER} "cd ${APP_PATH} && docker compose pull"
    - ssh ${DEPLOY_SERVER} "cd ${APP_PATH} && docker compose up -d"
    - echo "Deployment completed successfully."
  tags:
    - deploy
  only:
    - master
